"""adaptive learning schema

Revision ID: e08fff1a2721
Revises: 
Create Date: 2026-06-22 09:30:34.904497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import chess_coach_agent.db_models


# revision identifiers, used by Alembic.
revision: str = 'e08fff1a2721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', chess_coach_agent.db_models.Vector384(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source'), 'knowledge_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_theme'), 'knowledge_chunks', ['theme'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('username_normalized', sa.String(length=100), nullable=False),
    sa.Column('current_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username_normalized')
    )
    op.create_index(op.f('ix_players_platform'), 'players', ['platform'], unique=False)
    op.create_index(op.f('ix_players_username_normalized'), 'players', ['username_normalized'], unique=False)
    op.create_table('coach_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('focus_theme', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('accumulated_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_sessions_player_id'), 'coach_sessions', ['player_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('external_game_id', sa.String(length=64), nullable=False),
    sa.Column('white', sa.String(length=100), nullable=False),
    sa.Column('black', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('player_result', sa.String(length=12), nullable=False),
    sa.Column('player_color', sa.String(length=12), nullable=False),
    sa.Column('player_elo', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.String(length=24), nullable=False),
    sa.Column('time_control', sa.String(length=40), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'external_game_id')
    )
    op.create_index(op.f('ix_games_external_game_id'), 'games', ['external_game_id'], unique=False)
    op.create_index(op.f('ix_games_player_id'), 'games', ['player_id'], unique=False)
    op.create_table('player_memories',
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('recurring_themes', sa.JSON(), nullable=False),
    sa.Column('quiz_accuracy', sa.JSON(), nullable=False),
    sa.Column('mastered_positions', sa.Integer(), nullable=False),
    sa.Column('due_positions', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('focus_themes', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_player_id'), 'training_plans', ['player_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('training_plan', sa.JSON(), nullable=False),
    sa.Column('retrieval_notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('critical_moments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('external_moment_id', sa.String(length=80), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=40), nullable=False),
    sa.Column('played_san', sa.String(length=30), nullable=False),
    sa.Column('best_san', sa.String(length=30), nullable=True),
    sa.Column('fen_before', sa.Text(), nullable=False),
    sa.Column('fen_after', sa.Text(), nullable=False),
    sa.Column('eval_swing', sa.Float(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'external_moment_id')
    )
    op.create_index(op.f('ix_critical_moments_external_moment_id'), 'critical_moments', ['external_moment_id'], unique=False)
    op.create_index(op.f('ix_critical_moments_game_id'), 'critical_moments', ['game_id'], unique=False)
    op.create_index(op.f('ix_critical_moments_theme'), 'critical_moments', ['theme'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_history', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('through_sequence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', chess_coach_agent.db_models.Vector384(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['coach_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_summaries_player_id'), 'session_summaries', ['player_id'], unique=False)
    op.create_index(op.f('ix_session_summaries_session_id'), 'session_summaries', ['session_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('moment_id', sa.String(length=80), nullable=True),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['critical_moments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_player_id'), 'flashcards', ['player_id'], unique=False)
    op.create_index(op.f('ix_flashcards_theme'), 'flashcards', ['theme'], unique=False)
    op.create_table('stream_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'sequence')
    )
    op.create_index(op.f('ix_stream_events_message_id'), 'stream_events', ['message_id'], unique=False)
    op.create_table('training_positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('moment_id', sa.String(length=80), nullable=True),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('correct_move', sa.String(length=30), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('theme', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['critical_moments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_positions_plan_id'), 'training_positions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_training_positions_theme'), 'training_positions', ['theme'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.Column('submitted_move', sa.String(length=30), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('legal', sa.Boolean(), nullable=False),
    sa.Column('cp_loss', sa.Float(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['training_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_player_id'), 'quiz_attempts', ['player_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_position_id'), 'quiz_attempts', ['position_id'], unique=False)
    op.create_table('review_schedule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['training_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_index(op.f('ix_review_schedule_due_at'), 'review_schedule', ['due_at'], unique=False)
    op.create_index(op.f('ix_review_schedule_player_id'), 'review_schedule', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_schedule_player_id'), table_name='review_schedule')
    op.drop_index(op.f('ix_review_schedule_due_at'), table_name='review_schedule')
    op.drop_table('review_schedule')
    op.drop_index(op.f('ix_quiz_attempts_position_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_player_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_training_positions_theme'), table_name='training_positions')
    op.drop_index(op.f('ix_training_positions_plan_id'), table_name='training_positions')
    op.drop_table('training_positions')
    op.drop_index(op.f('ix_stream_events_message_id'), table_name='stream_events')
    op.drop_table('stream_events')
    op.drop_index(op.f('ix_flashcards_theme'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_player_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_session_summaries_session_id'), table_name='session_summaries')
    op.drop_index(op.f('ix_session_summaries_player_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_critical_moments_theme'), table_name='critical_moments')
    op.drop_index(op.f('ix_critical_moments_game_id'), table_name='critical_moments')
    op.drop_index(op.f('ix_critical_moments_external_moment_id'), table_name='critical_moments')
    op.drop_table('critical_moments')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_training_plans_player_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_table('player_memories')
    op.drop_index(op.f('ix_games_player_id'), table_name='games')
    op.drop_index(op.f('ix_games_external_game_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_coach_sessions_player_id'), table_name='coach_sessions')
    op.drop_table('coach_sessions')
    op.drop_index(op.f('ix_players_username_normalized'), table_name='players')
    op.drop_index(op.f('ix_players_platform'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_knowledge_chunks_theme'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
